"""add last_seen_at and last_synced_at to users

Revision ID: 01343f3d13b3
Revises: e6c3fa284531
Create Date: 2026-07-09 14:41:06.098361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01343f3d13b3"
down_revision: str | Sequence[str] | None = "e6c3fa284531"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Existing users predate activity tracking; treat them as seen now so they
    # stay in the nightly sync rotation until 30 days after their next visit.
    op.execute("UPDATE users SET last_seen_at = now() WHERE supabase_user_id IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_synced_at")
    op.drop_column("users", "last_seen_at")
    # ### end Alembic commands ###
