"""add sync_runs

Revision ID: 01896934ac8c
Revises: 1a7dd69c3a31
Create Date: 2026-08-16 15:32:25.265544

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01896934ac8c"
down_revision: str | Sequence[str] | None = "1a7dd69c3a31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_runs_active_created_at",
        "sync_runs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "ix_sync_runs_active_user",
        "sync_runs",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "ix_sync_runs_user_id_created_at", "sync_runs", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_runs_user_id_created_at", table_name="sync_runs")
    op.drop_index(
        "ix_sync_runs_active_user",
        table_name="sync_runs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        "ix_sync_runs_active_created_at",
        table_name="sync_runs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("sync_runs")
    # ### end Alembic commands ###
