"""add suggestions schema

Revision ID: 04d31169cc00
Revises: a9dcd2d9cc82
Create Date: 2026-07-06 18:54:30.555102

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04d31169cc00"
down_revision: str | Sequence[str] | None = "a9dcd2d9cc82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lastfm_similar_artists",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_key", sa.String(), nullable=False),
        sa.Column("mbid", sa.String(), nullable=True),
        sa.Column("match", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artist_id", "name_key"),
    )
    op.create_index(
        op.f("ix_lastfm_similar_artists_artist_id"),
        "lastfm_similar_artists",
        ["artist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lastfm_similar_artists_name_key"),
        "lastfm_similar_artists",
        ["name_key"],
        unique=False,
    )
    op.create_table(
        "user_artist_exclusions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "artist_id"),
    )
    op.create_index(
        op.f("ix_user_artist_exclusions_artist_id"),
        "user_artist_exclusions",
        ["artist_id"],
        unique=False,
    )
    op.add_column(
        "lastfm_artists", sa.Column("similar_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("user_artist_interests", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "include_known_artists", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "include_known_artists")
    op.drop_column("user_artist_interests", "weight")
    op.drop_column("lastfm_artists", "similar_synced_at")
    op.drop_index(op.f("ix_user_artist_exclusions_artist_id"), table_name="user_artist_exclusions")
    op.drop_table("user_artist_exclusions")
    op.drop_index(op.f("ix_lastfm_similar_artists_name_key"), table_name="lastfm_similar_artists")
    op.drop_index(op.f("ix_lastfm_similar_artists_artist_id"), table_name="lastfm_similar_artists")
    op.drop_table("lastfm_similar_artists")
    # ### end Alembic commands ###
