"""remove scrobbles and artist_count from lastfm_accounts

Revision ID: 5e37d0040133
Revises: 20123841322e
Create Date: 2026-07-09 08:03:23.366706

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e37d0040133"
down_revision: str | Sequence[str] | None = "20123841322e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lastfm_accounts", "artist_count")
    op.drop_column("lastfm_accounts", "playcount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lastfm_accounts", sa.Column("playcount", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "lastfm_accounts",
        sa.Column("artist_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
