"""add cities and user city

Revision ID: 6bf2cde164ec
Revises: e9940c9ec725
Create Date: 2026-07-05 19:18:25.970522

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bf2cde164ec"
down_revision: str | Sequence[str] | None = "e9940c9ec725"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "cities",
        sa.Column("geonameid", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ascii_name", sa.String(), nullable=False),
        sa.Column("admin1", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("geonameid"),
    )
    op.create_index(
        "ix_cities_ascii_name_trgm",
        "cities",
        ["ascii_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"ascii_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_cities_name_trgm",
        "cities",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.add_column("users", sa.Column("city_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_city_id"), "users", ["city_id"], unique=False)
    op.create_foreign_key(
        "users_city_id_fkey", "users", "cities", ["city_id"], ["geonameid"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_city_id_fkey", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_city_id"), table_name="users")
    op.drop_column("users", "city_id")
    op.drop_index(
        "ix_cities_name_trgm",
        table_name="cities",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_cities_ascii_name_trgm",
        table_name="cities",
        postgresql_using="gin",
        postgresql_ops={"ascii_name": "gin_trgm_ops"},
    )
    op.drop_table("cities")
    # ### end Alembic commands ###
